version: "3.3"

services:
  app:
    restart: always
    build: .
    command: flask run --host 0.0.0.0 --port 5000
    tty: true # pseudo-terminal - you can sea the console outputs in your terminal in vscode
    volumes: # where you can persostemtly save your data(so the next docker container will be able to retrieve it)
     - .:/usr/www/finalProject/pytweet
    ports: 
     - 5000:5000
    depends_on: 
     - db
    env_file: 
     - .env
    environment: 
     FLASK_APP: main.py # entry point
     FLASK_ENV: development

  db:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker_mysql
    ports: 
     - 3306:3306
    volumes:
     - ./docker/db/data:/var/lib/mysql
    env_file:
     - .env